-- CreateTable
CREATE TABLE "tasks" (
    "TASK_ID" BIGSERIAL NOT NULL,
    "TASK_TITLE" TEXT NOT NULL,
    "TASK_DESC" TEXT NOT NULL,
    "USER_ID" UUID NOT NULL,

    CONSTRAINT "tasks_pkey" PRIMARY KEY ("TASK_ID")
);

-- CreateTable
CREATE TABLE "users" (
    "USER_ID" UUID NOT NULL,
    "USER_NAME" TEXT NOT NULL,
    "USER_EMAIL" TEXT NOT NULL,
    "USER_PASSWORD" TEXT NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("USER_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "Uniq User" ON "users"("USER_EMAIL");

-- AddForeignKey
ALTER TABLE "tasks" ADD CONSTRAINT "User ID " FOREIGN KEY ("USER_ID") REFERENCES "users"("USER_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
